image: docker:latest

services:
  - name: docker:dind
    alias: docker

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: assign_BE
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build_job:
  stage: build
  tags:
    - build
  before_script:
    - unset DOCKER_HOST
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - cat "$ENV_FILE" > src/main/resources/.env
    - cat "
  script:
    - echo "빌드를 시작합니다...."
    - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest .
    - echo "도커허브에 푸시를 시작합니다..."
    - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE
  after_script:
    - docker logout
  only:
    - dev

deploy_job:
  stage: deploy
  tags:
    - deploy
  before_script:
    - unset DOCKER_HOST
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - echo "Deploying the project..."
    - docker stop assign_BE || true && docker rm assign_BE || true
    - docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
    - docker-compose up -d --build assign
  after_script:
    - docker image prune -f
    - docker logout
  when: on_success
  only:
    - dev