version: "3"
services:
  assign:
    container_name: assign_BE
    image: moonsunmean/assign_BE:latest
    ports:
      - "8080:8080"
    depends_on:
      - pgvectorDB
      - mongoDB
      - redis

  pgvectorDB:
    container_name: pgvectorDB
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: assign
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  mongoDB:
    container_name: mongoDB
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: assign
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongodb:/data/db
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data
    command: redis-server --appendonly no --loglevel warning
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    privileged: true
    volumes:
      - './config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/cache:/cache'
    environment:
      - DOCKER_TLS_CERTDIR=""
      - DOCKER_DRIVER=overlay2
