spring:
  application:
    name: assign-back
  config:
    import: optional:classpath:.env[.properties]

  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul

  data:
    mongodb:
      uri: ${MONGO_LOCAL_DB_URI}
      database: assign
      auto-index-creation: true

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 256

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    audience: ${AUTH0_AUDIENCE}