spring:
  application:
    name: assign-back

  okta:
    oauth2:
      issuer: https://dev-bdlzsc6hhucdmhb1.us.auth0.com/
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host: mongodb
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE_NAME}
      username: ${MONGODB_ROOT_NAME}
      password: ${MONGODB_ROOT_PASSWORD}
      auto-index-creation: true

