spring:
  application:
    name: assign-back
  config:
#    import: classpath:/.env[.properties]”
    import: optional:classpath:.env[.properties]
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  scheduling:
    enable: true

  datasource:
    url: jdbc:postgresql://pgvectorDB:5432/assign
    username: ${POSTGRES_PGVECTOR_DB_USERNAME}
    password: ${POSTGRES_PGVECTOR_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: assign
      auto-index-creation: true

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 256

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    audience: ${AUTH0_AUDIENCE}