spring:
  application:
    name: assign-back

  okta:
    oauth2:
      issuer: https://dev-bdlzsc6hhucdmhb1.us.auth0.com/
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
