spring:
  application:
    name: assign-back
  config:
#    import: classpath:/.env[.properties]”
    import: optional:classpath:.env[.properties]

  datasource:
    url: jdbc:postgresql://pgvectorDB:5432/assign
    username: ${POSTGRES_PGVECTOR_DB_USERNAME}
    password: ${POSTGRES_PGVECTOR_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

  okta:
    oauth2:
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

okta:
  oauth2:
    issuer: https://dev-aqq0w41zxvftci4m.jp.auth0.com/
