spring:
  application:
    name: assign-back

  datasource:
    url: jdbc:postgresql://pgvectorDB:5432/assign
    username: ${POSTGRE_PGVECTOR_DB_USERNAME}
    password: ${POSTGRE_PGVECTOR_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul



  okta:
    oauth2:
      issuer: https://dev-bdlzsc6hhucdmhb1.us.auth0.com/
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
