spring:
  application:
    name: assign-back

  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

  okta:
    oauth2:
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

okta:
  oauth2:
    issuer: https://dev-bdlzsc6hhucdmhb1.us.auth0.com/