spring:
  application:
    name: assign-back
  config:
    import: "optional:classpath:.env[.properties],optional:file:./.env"
  okta:
    oauth2:
      issuer: https://dev-bdlzsc6hhucdmhb1.us.auth0.com/
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul

  data:
    mongodb:
      uri: mongodb+srv://moon:moon@mycluster.wpc83.mongodb.net/?retryWrites=true&w=majority&appName=myCluster
      database: assign
      auto-index-creation: true

