spring:
  application:
    name: assign-back
  config:
    import: "optional:classpath:.env[.properties],optional:file:./.env"
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  scheduling:
    enable: true

  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul

  data:
    mongodb:
      uri: ${MONGO_LOCAL_DB_URI}
      database: assign
      auto-index-creation: true

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

  okta:
    oauth2:
      client-id: ${AUTH0_CLIENT_ID}
      client-secret: ${AUTH0_CLIENT_SECRET}

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}

