spring:
  application:
    name: assign-back
  config:
    import: "optional:classpath:.env[.properties],optional:file:./.env"
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  scheduling:
    enable: true
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
        default-profile-image: https://elice-assign-bucket.s3.ap-northeast-2.amazonaws.com/default_profile_image.jpeg
      region:
        static: ${AWS_S3_REGION}

  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul

  data:
    mongodb:
      uri: ${MONGO_LOCAL_DB_URI}
      database: assign
      auto-index-creation: true

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    audience: ${AUTH0_AUDIENCE}
